-- MySQL Script generated by MySQL Workbench
-- Fri Dec 12 22:00:19 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CONTROL_INVENTARIO
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CONTROL_INVENTARIO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CONTROL_INVENTARIO` DEFAULT CHARACTER SET utf8mb4 ;
USE `CONTROL_INVENTARIO` ;

-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`tipo_activo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`tipo_activo` (
  `id_tipo_activo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_tipo_activo`))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`objeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`objeto` (
  `id_objeto` INT NOT NULL AUTO_INCREMENT,
  `tipo_objeto` ENUM('acumulable', 'unico') NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `marca` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  `id_tipo_activo` INT NOT NULL,
  PRIMARY KEY (`id_objeto`),
  INDEX `id_tipo_activo_idx` (`id_tipo_activo` ASC) VISIBLE,
  CONSTRAINT `FK_objeto_tipoActivo`
    FOREIGN KEY (`id_tipo_activo`)
    REFERENCES `CONTROL_INVENTARIO`.`tipo_activo` (`id_tipo_activo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`item_serializado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`item_serializado` (
  `id_item_serializado` INT NOT NULL AUTO_INCREMENT,
  `id_objeto` INT NOT NULL,
  `serie` VARCHAR(45) NULL,
  `placa_activo` VARCHAR(45) NOT NULL,
  `estado_funcional` ENUM('OPERATIVO', 'FALLANDO', 'RETIRADO') NOT NULL,
  `estado_fisico` ENUM('BUENO', 'REGULAR', 'MALO') NOT NULL,
  `fecha_adquisicion` DATE NOT NULL,
  `fecha_puesto_servicio` DATE NULL,
  `n_garantia` VARCHAR(45) NULL,
  `fecha_inicio_garantia` DATE NULL,
  `fecha_fin_garantia` DATE NULL,
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_item_serializado`),
  INDEX `id_objeto_idx` (`id_objeto` ASC) VISIBLE,
  UNIQUE INDEX `serie_UNIQUE` (`serie` ASC) VISIBLE,
  UNIQUE INDEX `placa_activo_UNIQUE` (`placa_activo` ASC) VISIBLE,
  CONSTRAINT `FK_itemSerializado_objeto`
    FOREIGN KEY (`id_objeto`)
    REFERENCES `CONTROL_INVENTARIO`.`objeto` (`id_objeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nit` VARCHAR(15) NOT NULL COMMENT 'En la logica del programa verificar que se escriba el numero de verificación',
  `razon_social` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_proveedor`),
  UNIQUE INDEX `nit_UNIQUE` (`nit` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`factura` (
  `id_factura` INT NOT NULL AUTO_INCREMENT,
  `fecha_generacion` DATETIME NOT NULL,
  `id_proveedor` INT NOT NULL,
  `total_bruto` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `iva` DECIMAL(5,2) NULL DEFAULT 0,
  `valor_iva` DECIMAL(10,2) NULL DEFAULT 0,
  `retencion_fuente` DECIMAL(10,2) NULL DEFAULT 0,
  `descuento` DECIMAL(10,2) NULL DEFAULT 0,
  `valor_total` DECIMAL(10,2) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_factura`),
  INDEX `id_provedor_idx` (`id_proveedor` ASC) VISIBLE,
  constraint `CHK_factura_valores_positivos` check (
	`total_bruto` >= 0 AND 
    `iva` >= 0 AND
    `valor_iva` >= 0 AND
    `retencion_fuente` >= 0 AND
    `descuento` >= 0 AND
    `valor_total` >= 0
  ),
  CONSTRAINT `FK_factura_proveedor`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `CONTROL_INVENTARIO`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`objeto_acumulable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`objeto_acumulable` (
  `id_objeto_acumulable` INT NOT NULL AUTO_INCREMENT,
  `id_objeto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `fecha_adquisicion` DATE NULL,
  `forma_adquisicion` VARCHAR(45) NULL,
  `id_factura` INT NULL,
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_objeto_acumulable`),
  INDEX `id_objeto_idx` (`id_objeto` ASC) VISIBLE,
  INDEX `id_factura_idx` (`id_factura` ASC) VISIBLE,
  CONSTRAINT `CHK_cantidad_positiva` CHECK (`cantidad` > 0),
  CONSTRAINT `FK_objetoAcumulable_objeto`
    FOREIGN KEY (`id_objeto`)
    REFERENCES `CONTROL_INVENTARIO`.`objeto` (`id_objeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_objetoAcumulable_factura`
    FOREIGN KEY (`id_factura`)
    REFERENCES `CONTROL_INVENTARIO`.`factura` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`detalle_factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`detalle_factura` (
  `id_detalle_factura` INT NOT NULL AUTO_INCREMENT,
  `id_factura` INT NOT NULL,
  `id_objeto` INT NOT NULL,
  `id_item_serializado` INT NULL,
  `descripcion_factura` TEXT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  `valor_bruto` DECIMAL(10,2) NOT NULL,
  `tasa_impuesto` DECIMAL(5,2) NOT NULL DEFAULT 0.00,
  `valor_impto_cargo` DECIMAL(10,2) NOT NULL,
  `descuento` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `valor_total` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_detalle_factura`),
  INDEX `id_factura_idx` (`id_factura` ASC) VISIBLE,
  INDEX `id_objeto_idx` (`id_objeto` ASC) VISIBLE,
  UNIQUE INDEX `id_item_serializado_UNIQUE` (`id_item_serializado` ASC) VISIBLE,
  CONSTRAINT `CHK_detalle_factura_valores_positivos` CHECK (
	`cantidad` >= 1 AND
    `precio_unitario` >= 0 AND
    `valor_bruto` >= 0 AND
    `tasa_impuesto` >= 0 AND
    `valor_impto_cargo` >= 0 AND
    `descuento` >= 0 AND
    `valor_total` >= 0
  ),
  CONSTRAINT `FK_detalleFactura_factura`
    FOREIGN KEY (`id_factura`)
    REFERENCES `CONTROL_INVENTARIO`.`factura` (`id_factura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_detalleFactura_objeto`
    FOREIGN KEY (`id_objeto`)
    REFERENCES `CONTROL_INVENTARIO`.`objeto` (`id_objeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_detalleFactura_itemSerializado`
    FOREIGN KEY (`id_item_serializado`)
    REFERENCES `CONTROL_INVENTARIO`.`item_serializado` (`id_item_serializado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`ubicacion` (
  `id_ubicacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `id_zona_padre` INT NULL,
  PRIMARY KEY (`id_ubicacion`),
  INDEX `id_zona_padre_idx` (`id_zona_padre` ASC) VISIBLE,
  CONSTRAINT `FK_zona_ubicacion`
    FOREIGN KEY (`id_zona_padre`)
    REFERENCES `CONTROL_INVENTARIO`.`ubicacion` (`id_ubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`inventario` (
  `id_inventario` INT NOT NULL AUTO_INCREMENT,
  `id_objeto` INT NOT NULL,
  `id_item_serializado` INT NULL,
  `cantidad_actual` INT NOT NULL,
  `id_ubicacion` INT NOT NULL,
  `estado_actual` ENUM('OPERATIVO', 'FALLANDO', 'RETIRADO') NOT NULL,
  `fecha_ultima_actualizacion` DATETIME NOT NULL,
  PRIMARY KEY (`id_inventario`),
  INDEX `id_objeto_idx` (`id_objeto` ASC) VISIBLE,
  INDEX `id_item_serializado_idx` (`id_item_serializado` ASC) VISIBLE,
  INDEX `id_ubicacion_idx` (`id_ubicacion` ASC) VISIBLE,
  CONSTRAINT `CHK_inventario_valor_positivo` CHECK (`cantidad_actual` >= 0),
  CONSTRAINT `FK_inventario_objeto`
    FOREIGN KEY (`id_objeto`)
    REFERENCES `CONTROL_INVENTARIO`.`objeto` (`id_objeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_inventario_itemSerializado`
    FOREIGN KEY (`id_item_serializado`)
    REFERENCES `CONTROL_INVENTARIO`.`item_serializado` (`id_item_serializado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_inventario_ubicacion`
    FOREIGN KEY (`id_ubicacion`)
    REFERENCES `CONTROL_INVENTARIO`.`ubicacion` (`id_ubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`persona` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `primer_nombre` VARCHAR(45) NOT NULL,
  `segundo_nombre` VARCHAR(45) NULL,
  `primer_apellido` VARCHAR(45) NOT NULL,
  `segundo_apellido` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(250) NOT NULL,
  `direccion` VARCHAR(100) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_persona`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`responsable_objeto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`responsable_objeto` (
  `id_responsable_objeto` INT NOT NULL AUTO_INCREMENT,
  `id_inventario` INT NOT NULL,
  `id_persona` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_responsable_objeto`),
  INDEX `id_inventario_idx` (`id_inventario` ASC) VISIBLE,
  INDEX `id_persona_idx` (`id_persona` ASC) VISIBLE,
  CONSTRAINT `FK_responsableObjeto_inventario`
    FOREIGN KEY (`id_inventario`)
    REFERENCES `CONTROL_INVENTARIO`.`inventario` (`id_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_responsableObjeto_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `CONTROL_INVENTARIO`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`responsable_ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`responsable_ubicacion` (
  `id_responsable_ubicacion` INT NOT NULL AUTO_INCREMENT,
  `id_ubicacion` INT NOT NULL,
  `id_persona` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NULL,
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_responsable_ubicacion`),
  INDEX `id_ubicacion_idx` (`id_ubicacion` ASC) VISIBLE,
  INDEX `id_persona_idx` (`id_persona` ASC) VISIBLE,
  CONSTRAINT `FK_responsableUbicacion_ubicacion`
    FOREIGN KEY (`id_ubicacion`)
    REFERENCES `CONTROL_INVENTARIO`.`ubicacion` (`id_ubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_responsableUbicacion_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `CONTROL_INVENTARIO`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`tipo_movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`tipo_movimiento` (
  `id_tipo_movimiento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_tipo_movimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`movimiento` (
  `id_movimiento` INT NOT NULL AUTO_INCREMENT,
  `fecha_movimiento` DATE NOT NULL,
  `id_tipo_movimiento` INT NOT NULL,
  PRIMARY KEY (`id_movimiento`),
  INDEX `FK_movimiento__tipoMovimiento_idx` (`id_tipo_movimiento` ASC) VISIBLE,
  CONSTRAINT `FK_movimiento__tipoMovimiento`
    FOREIGN KEY (`id_tipo_movimiento`)
    REFERENCES `CONTROL_INVENTARIO`.`tipo_movimiento` (`id_tipo_movimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`detalle_movimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`detalle_movimiento` (
  `id_detalle_movimiento` INT NOT NULL AUTO_INCREMENT,
  `id_movimiento` INT NOT NULL,
  `id_objeto` INT NOT NULL,
  `id_item_serializado` INT NULL,
  `id_inventario_origen` INT NULL,
  `id_inventario_destino` INT NULL,
  `id_ubicacion_origen` INT NULL,
  `id_ubicacion_destino` INT NOT NULL,
  `cantidad_afectada` INT NOT NULL,
  `observaciones` VARCHAR(100) NULL,
  PRIMARY KEY (`id_detalle_movimiento`),
  INDEX `id_movimiento_idx` (`id_movimiento` ASC) VISIBLE,
  INDEX `id_objeto_idx` (`id_objeto` ASC) VISIBLE,
  INDEX `id_item_serializado_idx` (`id_item_serializado` ASC) VISIBLE,
  INDEX `id_inventario_origen_idx` (`id_inventario_origen` ASC) VISIBLE,
  INDEX `id_inventario_destino_idx` (`id_inventario_destino` ASC) VISIBLE,
  INDEX `id_ubicacion_origen_idx` (`id_ubicacion_origen` ASC) VISIBLE,
  INDEX `id_ubicacion_destino_idx` (`id_ubicacion_destino` ASC) VISIBLE,
  CONSTRAINT `CHK_detalle_movimiento_valor_mayor_1` CHECK (`cantidad_afectada` >= 1),
  CONSTRAINT `FK_detalleMovimiento_movimiento`
    FOREIGN KEY (`id_movimiento`)
    REFERENCES `CONTROL_INVENTARIO`.`movimiento` (`id_movimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_detalleMovimiento_objeto`
    FOREIGN KEY (`id_objeto`)
    REFERENCES `CONTROL_INVENTARIO`.`objeto` (`id_objeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_detalleMovimiento_itemSerializado`
    FOREIGN KEY (`id_item_serializado`)
    REFERENCES `CONTROL_INVENTARIO`.`item_serializado` (`id_item_serializado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_detalleMovimiento_inventarioOrigen`
    FOREIGN KEY (`id_inventario_origen`)
    REFERENCES `CONTROL_INVENTARIO`.`inventario` (`id_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_detalleMovimiento_inventarioDestino`
    FOREIGN KEY (`id_inventario_destino`)
    REFERENCES `CONTROL_INVENTARIO`.`inventario` (`id_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_detalleMovimiento_ubicacionOrigen`
    FOREIGN KEY (`id_ubicacion_origen`)
    REFERENCES `CONTROL_INVENTARIO`.`ubicacion` (`id_ubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_detalleMovimiento_ubicacionDestino`
    FOREIGN KEY (`id_ubicacion_destino`)
    REFERENCES `CONTROL_INVENTARIO`.`ubicacion` (`id_ubicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`rol` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NOT NULL,
  `nombre_usuario` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(200) NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `nombre_usuario_UNIQUE` (`nombre_usuario` ASC) VISIBLE,
  INDEX `id_rol_idx` (`id_rol` ASC) VISIBLE,
  INDEX `id_persona_idx` (`id_persona` ASC) VISIBLE,
  CONSTRAINT `FK_usuario_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `CONTROL_INVENTARIO`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_usuario_persona`
    FOREIGN KEY (`id_persona`)
    REFERENCES `CONTROL_INVENTARIO`.`persona` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`auditoria` (
  `id_log` INT NOT NULL AUTO_INCREMENT,
  `nombre_tabla` VARCHAR(20) NOT NULL,
  `id_registro_afectado` INT NOT NULL,
  `accion` ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
  `id_usuario` INT NOT NULL,
  `fecha_hora` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_log`),
  INDEX `id_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `FK_auditoria_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `CONTROL_INVENTARIO`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`operacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`operacion` (
  `id_operacion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_operacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`modulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`modulo` (
  `id_modulo` INT NOT NULL AUTO_INCREMENT,
  `nombre_tabla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`permiso` (
  `id_permiso` INT NOT NULL AUTO_INCREMENT,
  `id_modulo` INT NOT NULL,
  `id_operacion` INT NOT NULL,
  PRIMARY KEY (`id_permiso`),
  INDEX `id_modulo_idx` (`id_modulo` ASC) VISIBLE,
  INDEX `id_operacion_idx` (`id_operacion` ASC) INVISIBLE,
  UNIQUE INDEX `UK_modulo_operacion` (`id_modulo` ASC, `id_operacion` ASC) VISIBLE,
  CONSTRAINT `FK_modulo_permiso`
    FOREIGN KEY (`id_modulo`)
    REFERENCES `CONTROL_INVENTARIO`.`modulo` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_operacion_permiso`
    FOREIGN KEY (`id_operacion`)
    REFERENCES `CONTROL_INVENTARIO`.`operacion` (`id_operacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CONTROL_INVENTARIO`.`permiso_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CONTROL_INVENTARIO`.`permiso_rol` (
  `id_rol` INT NOT NULL,
  `id_permiso` INT NOT NULL,
  PRIMARY KEY (`id_rol`, `id_permiso`),
  INDEX `id_rol_idx` (`id_rol` ASC) VISIBLE,
  INDEX `id_permiso_idx` (`id_permiso` ASC) VISIBLE,
  CONSTRAINT `FK_permisoRol_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `CONTROL_INVENTARIO`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_permisoRol_permiso`
    FOREIGN KEY (`id_permiso`)
    REFERENCES `CONTROL_INVENTARIO`.`permiso` (`id_permiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

----


